# Generated by Django 3.1 on 2021-08-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=80)),
                ('edificio', models.CharField(blank=True, max_length=20, null=True)),
                ('numero', models.IntegerField()),
                ('colonia', models.CharField(max_length=80)),
                ('delegacion', models.CharField(max_length=80)),
                ('cp', models.IntegerField()),
                ('ciudad', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'domicilio',
                'db_table': 'Domicilios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('password', models.CharField(blank=True, max_length=64)),
                ('username', models.CharField(max_length=255)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.domicilio')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'db_table': 'Usuarios',
                'ordering': ['phone'],
            },
        ),
    ]
